### ISSUE TITLE
ERD CLOUD  피드백

### ISSUE THREAD

**Issue by Reading-Snail** [nogariProject/nogari#20]
MEM -> MEMBER
FIRST_YN -> FRIST_LOGIN_YN 
이 좀더 좋지 않을까요?

초기 개발자가 아니어도 쉽게 읽을 수 있는 코드가 지향점이 되어야 되지 않나 질문을 던져봅니다.
해서 NM과 같은 약어도 SQL Editor에서 자동완성 기능을 사용한다면 그리 개발속도를 저해하는 부분이 아닐 것 같은데
꼭 줄여야 되는 부분인지 고민해봐야 되는 부분 같습니다.

물론 Registration과 같은 긴 단어들에 대해서는 REG와 같은 약어 사용에 찬성합니다.

**Comment by iknowahra** [comment]
반영하기로 회의중에 결정함
