### ISSUE TITLE
오라클 TimeZone 설정

### ISSUE THREAD

**Issue by wlsdnd221** [nogariProject/nogari#26]
### 1. 이슈내용
오라클 SYSDATE, SYSTIMESTAMP의 경우 **'DB OS시간'** 기준 현재 시각을 출력합니다.
현재 저희 DB의 경우, 세션시간은 'Asia/Seoul'로 확인되지만 DBTimeZone은 "+00:00"으로 시차 계산(서울은 UTC보다 9시간 빠르다)
이 적용되지 않았습니다.

### 2. 참조코드
 - 현재 셋팅확인 : `SELECT SESSIONTIMEZONE, DBTIMEZONE, SYSTIMESTAMP, SYSDATE FROM DUAL;`
 - TimeZone목록 : `SELECT * FROM V$TIMEZONE_NAMES;`
 - 세션 시간대 변경 : `ALTER SESSION SET TIME_ZONE = 'Asia/Seoul';`
 - DB 시간대 변경 : `ALTER DATABASE SET TIME_ZONE = '+09:00';`

### 3. 위 내용으로 추가되는 이슈
 - DB 시간대를 강제로 설정 가능하나, 강제 설정 시 섬머타임까지 적용이 되는가?
 - ORACLE CLOUD에서 설정법을 확인해 봐야 함

**Comment by Reading-Snail** [comment]
[오라클 클라우드 DB 시간대 설정](https://okky.kr/questions/1020254)
2년전 글이긴 한데 근본적으로는 불가능 한 것 아닌가 하는 생각이 드네요

**Comment by iknowahra** [comment]
CURRENT_DATE : 2024-01-11 14:00:28.000
CURRENT_TIMESTAMP : 2024-01-11 14:00:28.033 +0900
SYSDATE : 2024-01-11 05:00:28.000

**Comment by Reading-Snail** [comment]
2024-01-11 14:00:28.000 => CURRENT_DATE
2024-01-11 14:00:28.033 +0900 => CURRENT_TIMESTAMP 
(즉, 더 세밀한 값이 필요할 경우 CURRENT_TIMESTAMP를 사용합니다.
