### ISSUE TITLE
DB 사용 쿼리 스크립트 저장 필요 여부

### ISSUE THREAD

**Issue by KOTAEU** [nogariProject/nogari#28]
DB 생성 및 조작에 필요한 쿼리 스크립트를 각자 보관하면 되는지, 어딘가 위치를 지정하여 다 같이 관리 할 것인지 알고 싶습니다.

**Comment by Reading-Snail** [comment]
저는 개인적으로 schema-h2.sql 파일에 저장하고 있습니다. (H2 DB 사용시 해당 Schema 
해당 파일을 resources 폴더 하위에 두어 로컬환경에서 테스트 할 때, H2 DB에 자동으로 DDL이 적용 될 수 있는 구조입니다.
ORACLE CLOUD 환경을 쓰는 것도 좋지만 H2 DB를 사용하여 스프링 프레임워크가 정상 작동하는지를 로컬 환경에서 확인해가면서 개발하는 것도 좋을 것 같습니다.
