### ISSUE TITLE
[CRUD] dept

### ISSUE THREAD

**Issue by Yseolcoding** [nogariProject/nogari#70]
- [x]  테이블 생성
-  Create
   - [ ] 테스트 코드 작성
   - [x] 코드 구현
- Read
   - [ ] 테스트 코드 작성
   - [x] 코드 구현
- Update
   - [ ] 테스트 코드 작성
   - [x] 코드 구현
- Delete
   - [ ] 테스트 코드 작성
   - [x] 코드 구현

**Comment by Reading-Snail** [comment]
Mapper.xml 주석 코드리뷰 감사드립니다!

완료!
